// Mocks generated by Mockito 5.4.6 from annotations
// in trip_planner/test/providers/activity_image_retry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:trip_planner/models/activity.dart' as _i3;
import 'package:trip_planner/models/activity_image.dart' as _i9;
import 'package:trip_planner/models/brainstorm_idea.dart' as _i8;
import 'package:trip_planner/repositories/activity_repository.dart' as _i7;
import 'package:trip_planner/services/image_service.dart' as _i2;
import 'package:trip_planner/services/image_storage_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlatformFile_0 extends _i1.SmartFake implements _i2.PlatformFile {
  _FakePlatformFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivity_1 extends _i1.SmartFake implements _i3.Activity {
  _FakeActivity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i2.ImageService {
  MockImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PlatformFile?> pickFromGallery() => (super.noSuchMethod(
        Invocation.method(
          #pickFromGallery,
          [],
        ),
        returnValue: _i4.Future<_i2.PlatformFile?>.value(),
      ) as _i4.Future<_i2.PlatformFile?>);

  @override
  _i4.Future<_i2.PlatformFile?> pickFromCamera() => (super.noSuchMethod(
        Invocation.method(
          #pickFromCamera,
          [],
        ),
        returnValue: _i4.Future<_i2.PlatformFile?>.value(),
      ) as _i4.Future<_i2.PlatformFile?>);

  @override
  _i4.Future<_i2.PlatformFile> compressImage(
    _i2.PlatformFile? imageFile, {
    int? maxSizeBytes = 3145728,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressImage,
          [imageFile],
          {#maxSizeBytes: maxSizeBytes},
        ),
        returnValue: _i4.Future<_i2.PlatformFile>.value(_FakePlatformFile_0(
          this,
          Invocation.method(
            #compressImage,
            [imageFile],
            {#maxSizeBytes: maxSizeBytes},
          ),
        )),
      ) as _i4.Future<_i2.PlatformFile>);

  @override
  _i4.Future<int> getFileSize(_i2.PlatformFile? file) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [file],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.PlatformFile> generateThumbnail(
    _i2.PlatformFile? imageFile, {
    int? maxWidth = 300,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateThumbnail,
          [imageFile],
          {#maxWidth: maxWidth},
        ),
        returnValue: _i4.Future<_i2.PlatformFile>.value(_FakePlatformFile_0(
          this,
          Invocation.method(
            #generateThumbnail,
            [imageFile],
            {#maxWidth: maxWidth},
          ),
        )),
      ) as _i4.Future<_i2.PlatformFile>);
}

/// A class which mocks [ImageStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageStorageService extends _i1.Mock
    implements _i5.ImageStorageService {
  MockImageStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> uploadImage(
    _i2.PlatformFile? imageFile,
    String? storagePath, {
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [
            imageFile,
            storagePath,
          ],
          {#onProgress: onProgress},
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [
              imageFile,
              storagePath,
            ],
            {#onProgress: onProgress},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteImage(String? storagePath) => (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [storagePath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getDownloadUrl(String? storagePath) => (super.noSuchMethod(
        Invocation.method(
          #getDownloadUrl,
          [storagePath],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getDownloadUrl,
            [storagePath],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i7.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i3.Activity>> getTripActivities(String? tripId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripActivities,
          [tripId],
        ),
        returnValue: _i4.Stream<List<_i3.Activity>>.empty(),
      ) as _i4.Stream<List<_i3.Activity>>);

  @override
  _i4.Future<_i3.Activity> createActivity(_i3.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivity,
          [activity],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #createActivity,
            [activity],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> updateActivity(_i3.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [activity],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #updateActivity,
            [activity],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<void> deleteActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #deleteActivity,
          [activityId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.Activity> addBrainstormIdea(
    String? activityId,
    _i8.BrainstormIdea? idea,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBrainstormIdea,
          [
            activityId,
            idea,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #addBrainstormIdea,
            [
              activityId,
              idea,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> removeBrainstormIdea(
    String? activityId,
    String? ideaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBrainstormIdea,
          [
            activityId,
            ideaId,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #removeBrainstormIdea,
            [
              activityId,
              ideaId,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> reorderBrainstormIdeas(
    String? activityId,
    List<String>? ideaIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderBrainstormIdeas,
          [
            activityId,
            ideaIds,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #reorderBrainstormIdeas,
            [
              activityId,
              ideaIds,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> assignActivityToDay(
    String? activityId,
    String? day,
    int? dayOrder, {
    String? timeSlot,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignActivityToDay,
          [
            activityId,
            day,
            dayOrder,
          ],
          {#timeSlot: timeSlot},
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #assignActivityToDay,
            [
              activityId,
              day,
              dayOrder,
            ],
            {#timeSlot: timeSlot},
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> moveActivityToPool(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveActivityToPool,
          [activityId],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #moveActivityToPool,
            [activityId],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<void> reorderActivitiesInDay(
    String? tripId,
    String? day,
    List<String>? activityIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderActivitiesInDay,
          [
            tripId,
            day,
            activityIds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.Activity?> getActivityById(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityById,
          [activityId],
        ),
        returnValue: _i4.Future<_i3.Activity?>.value(),
      ) as _i4.Future<_i3.Activity?>);

  @override
  _i4.Future<_i3.Activity> addImageToActivity(
    String? activityId,
    _i9.ActivityImage? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addImageToActivity,
          [
            activityId,
            image,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #addImageToActivity,
            [
              activityId,
              image,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> removeImageFromActivity(
    String? activityId,
    String? imageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeImageFromActivity,
          [
            activityId,
            imageId,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #removeImageFromActivity,
            [
              activityId,
              imageId,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> reorderActivityImages(
    String? activityId,
    List<String>? imageIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderActivityImages,
          [
            activityId,
            imageIds,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #reorderActivityImages,
            [
              activityId,
              imageIds,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);

  @override
  _i4.Future<_i3.Activity> updateImageCaption(
    String? activityId,
    String? imageId,
    String? caption,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageCaption,
          [
            activityId,
            imageId,
            caption,
          ],
        ),
        returnValue: _i4.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #updateImageCaption,
            [
              activityId,
              imageId,
              caption,
            ],
          ),
        )),
      ) as _i4.Future<_i3.Activity>);
}

/// A class which mocks [PlatformFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformFile extends _i1.Mock implements _i2.PlatformFile {
  MockPlatformFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i4.Future<List<int>> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
