name: trip_planner
description: A trip planner app to collaborate with friends on travel ideas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  
  # Navigation
  go_router: ^16.0.0
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  uuid: ^4.0.0
  
  # Utils
  freezed_annotation: ^3.0.0 
  json_annotation: ^4.8.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/