name: trip_planner
description: A trip planner app to collaborate with friends on travel ideas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  
  # Navigation
  go_router: ^16.0.0
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.8
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  uuid: ^4.0.0
  
  # Image Management
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  permission_handler: ^11.3.1
  
  # Utils
  freezed_annotation: ^3.0.0 
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  json_serializable: ^6.7.1
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/