// Mocks generated by Mockito 5.4.6 from annotations
// in trip_planner/test/screens/trip_detail_drag_drop_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner/models/activity.dart' as _i3;
import 'package:trip_planner/models/brainstorm_idea.dart' as _i7;
import 'package:trip_planner/models/trip.dart' as _i2;
import 'package:trip_planner/repositories/activity_repository.dart' as _i6;
import 'package:trip_planner/repositories/trip_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTrip_0 extends _i1.SmartFake implements _i2.Trip {
  _FakeTrip_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivity_1 extends _i1.SmartFake implements _i3.Activity {
  _FakeActivity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripRepository extends _i1.Mock implements _i4.TripRepository {
  MockTripRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Trip>> getUserTrips(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTrips,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i2.Trip>>.empty(),
      ) as _i5.Stream<List<_i2.Trip>>);

  @override
  _i5.Future<_i2.Trip> createTrip(_i2.Trip? trip) => (super.noSuchMethod(
        Invocation.method(
          #createTrip,
          [trip],
        ),
        returnValue: _i5.Future<_i2.Trip>.value(_FakeTrip_0(
          this,
          Invocation.method(
            #createTrip,
            [trip],
          ),
        )),
      ) as _i5.Future<_i2.Trip>);

  @override
  _i5.Future<_i2.Trip> updateTrip(_i2.Trip? trip) => (super.noSuchMethod(
        Invocation.method(
          #updateTrip,
          [trip],
        ),
        returnValue: _i5.Future<_i2.Trip>.value(_FakeTrip_0(
          this,
          Invocation.method(
            #updateTrip,
            [trip],
          ),
        )),
      ) as _i5.Future<_i2.Trip>);

  @override
  _i5.Future<void> deleteTrip(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrip,
          [tripId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCollaborator(
    String? tripId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCollaborator,
          [
            tripId,
            email,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Trip?> getTripById(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #getTripById,
          [tripId],
        ),
        returnValue: _i5.Future<_i2.Trip?>.value(),
      ) as _i5.Future<_i2.Trip?>);
}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i6.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i3.Activity>> getTripActivities(String? tripId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTripActivities,
          [tripId],
        ),
        returnValue: _i5.Stream<List<_i3.Activity>>.empty(),
      ) as _i5.Stream<List<_i3.Activity>>);

  @override
  _i5.Future<_i3.Activity> createActivity(_i3.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivity,
          [activity],
        ),
        returnValue: _i5.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #createActivity,
            [activity],
          ),
        )),
      ) as _i5.Future<_i3.Activity>);

  @override
  _i5.Future<_i3.Activity> updateActivity(_i3.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [activity],
        ),
        returnValue: _i5.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #updateActivity,
            [activity],
          ),
        )),
      ) as _i5.Future<_i3.Activity>);

  @override
  _i5.Future<void> deleteActivity(String? activityId) => (super.noSuchMethod(
        Invocation.method(
          #deleteActivity,
          [activityId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Activity> addBrainstormIdea(
    String? activityId,
    _i7.BrainstormIdea? idea,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBrainstormIdea,
          [
            activityId,
            idea,
          ],
        ),
        returnValue: _i5.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #addBrainstormIdea,
            [
              activityId,
              idea,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Activity>);

  @override
  _i5.Future<_i3.Activity> removeBrainstormIdea(
    String? activityId,
    String? ideaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBrainstormIdea,
          [
            activityId,
            ideaId,
          ],
        ),
        returnValue: _i5.Future<_i3.Activity>.value(_FakeActivity_1(
          this,
          Invocation.method(
            #removeBrainstormIdea,
            [
              activityId,
              ideaId,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Activity>);

  @override
  _i5.Future<_i3.Activity?> getActivityById(String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityById,
          [activityId],
        ),
        returnValue: _i5.Future<_i3.Activity?>.value(),
      ) as _i5.Future<_i3.Activity?>);
}
